name: firebasetodo
description: A Firebase CRUD application for Experiment 10.
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Packages required for this experiment
  firebase_core: ^2.27.1 
  cloud_firestore: ^4.15.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.5.1

flutter:
  uses-material-design: true